language: node_js
node_js:
    - '12'
os:
    - osx
env:
    global:
        secure: qOagTTe/0JSg4iR21jYyhx023fWvT0BNdVKs9CHoxfql/V6uoOU6gbMdilW1VmmAMKfzPnr2vWLDwEAqTMG7Qe/ZPkkpI769ykPKmGgYU9pFX/n78UOw5wCCqjQozUgXgkWQjIPxshQN4A3xgrMQaZG1s/3kbRJbCLqzs6Enex+hoc1Is7T4yCmCdkqQDK39wzrzsEOvxYVBCuJd1dcq9/pZG+TjtTOrcJLGxPpzQ6ntdc0tuPiQUkbprIyP82XrKc44QdH/Gxvi703Kkde/RawyvRjas5WcS1mmzigW4QgxFrqDBjwKMA4YW6CHi5X7iaJUDx/g9YXh5pJauX5vjrRNKXM2ixqC6ka4tOcLXWWVE+5sJx7pr2KWZgkxsOjSfeGAYKOQ5H1piYLX054vj2awbSa3KpP91whv4bWUtXsqVquU26/u3pu5SyhfJQADm92lmszFs9rhwiqaZb5iyphtgSCRFWv6q3Pgs1vdl34yQx58Ce9R1yZxF0aUjLCE+697zRPv7I5m0hLvxG83djL07Lj0eoyUUymwWkNLlS/56K5zr9S7MYuJEWwT4Pzc7Nr9VN+IYODn6EV99hmvEoJhcKu7wHKIsIquaCvCKQ8531Eoc+Ii7KCOQ/FArnU18h87o8LGKcr4FAdw1+RFkOqL0OVJ4zb5YmXKQhoL1yk=
sudo: false
before_install:
    - if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
    - yarn install
script:
    - yarn run compile:dev
    - yarn test
after_script:
    - node ./server/node_modules/coveralls/bin/coveralls.js -v < ./server/coverage/lcov.info
before_deploy:
    - yarn global add vsce
    - yarn run package
deploy:
    - provider: script
      script: yarn run publish -- -p $VS_TOKEN
      skip_cleanup: true
      on:
          repo: xsburg/vscode-javascript-booster
          tags: true
          condition: '$TRAVIS_OS_NAME = osx'
    - provider: releases
      api_key:
          secure: onSI3tk+3s1iwE/8ylDgMuU1B8k4Kep/QKcWvxX5+i0dW/2FioybgaVAjVDxKPMrkj9Z65bgOccHArL8gInf1zjjU3hi97/WHYXReqUfW6cCw1CElhRQo7cq+2o4D5T0vkDzd1gT4e5nRMI2+jSjoUP7pvxg9/LwXvl7h7Ay//3PCGWYz77cNjYVb3n5uho5ckBe0Trg8LzHvYb64BFa44D3pfYUBEUeWeS8nFJDARHgpDH8JIWtACSZaY6hkl4fSJMpaXpJ0SxPpe1qAJRgac3h5o38sutQK5PgZ3fLPxAbuut+T2TwMpURCBbgF/djoElVxQEHkRf9Ux7FSS0kL/0MCRNxJsiZ2EOUG36MIBSYEr0mR2Xe/jJngpktC0x8MQEJcaJcy/RZ5r2PXDTWonPYToacp7Pem/5zsEhEAbCeMCRxy1/xwNj0ghfXULCSIOwK0PWBZiBxoOKwaYA5Ty1RnSFYFV185OHIbQSpjjN7nHJRWYWt9IXVI81TmJu/ZIL9jBI+SiwRE/m/L9xg8d2lLX/3JcGHKoVaWNjclOo5t/Qegy41VUiSrs8kCmnOuKIU9bcLXD01ubItoApXl3K3lh8MUNs7FCjMwbtb2nNOETgCKumTihWw69bQ7csq+k9jJ9xgYNLt13RgJ9CGCrv8WqnGUg4c6DhPDnhsfPQ=
      skip_cleanup: true
      file_glob: true
      file: 'client/*.vsix'
      on:
          repo: xsburg/vscode-javascript-booster
          tags: true
          condition: '$TRAVIS_OS_NAME = osx'
notifications:
    email:
        on_success: change
