language: node_js
node_js:
    - '10'
os:
    - osx
env:
    global:
        secure: qOagTTe/0JSg4iR21jYyhx023fWvT0BNdVKs9CHoxfql/V6uoOU6gbMdilW1VmmAMKfzPnr2vWLDwEAqTMG7Qe/ZPkkpI769ykPKmGgYU9pFX/n78UOw5wCCqjQozUgXgkWQjIPxshQN4A3xgrMQaZG1s/3kbRJbCLqzs6Enex+hoc1Is7T4yCmCdkqQDK39wzrzsEOvxYVBCuJd1dcq9/pZG+TjtTOrcJLGxPpzQ6ntdc0tuPiQUkbprIyP82XrKc44QdH/Gxvi703Kkde/RawyvRjas5WcS1mmzigW4QgxFrqDBjwKMA4YW6CHi5X7iaJUDx/g9YXh5pJauX5vjrRNKXM2ixqC6ka4tOcLXWWVE+5sJx7pr2KWZgkxsOjSfeGAYKOQ5H1piYLX054vj2awbSa3KpP91whv4bWUtXsqVquU26/u3pu5SyhfJQADm92lmszFs9rhwiqaZb5iyphtgSCRFWv6q3Pgs1vdl34yQx58Ce9R1yZxF0aUjLCE+697zRPv7I5m0hLvxG83djL07Lj0eoyUUymwWkNLlS/56K5zr9S7MYuJEWwT4Pzc7Nr9VN+IYODn6EV99hmvEoJhcKu7wHKIsIquaCvCKQ8531Eoc+Ii7KCOQ/FArnU18h87o8LGKcr4FAdw1+RFkOqL0OVJ4zb5YmXKQhoL1yk=
sudo: false
before_install:
    - npm install -g npm@6.7.x
    - if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
    - npm install
script:
    - npm run compile:dev
    - npm test
after_script:
    - node ./server/node_modules/coveralls/bin/coveralls.js -v < ./server/coverage/lcov.info
before_deploy:
    - npm install -g vsce
    - npm run package
deploy:
    - provider: script
      script: vsce publish -p $VS_TOKEN
      skip_cleanup: true
      on:
          repo: xsburg/vscode-javascript-booster
          tags: true
          condition: '$TRAVIS_OS_NAME = osx'
    - provider: releases
      api_key:
          secure: gs6iJkqvW4psjgFNaLIzp6QF8ceCUsSkQpeAlnbWUmlkUvCZjF2PN0vOf7sXD+VgMfSV6jS3lho0jcQZCp8ZFf/G1A25WMYThmHLzZGUGNXhXIMlJ5qPqbtbmvtnIRCuW9ZqzqNH/WB1XXArn1/qlJ5WPsU3EZpJb0ZZjmYHZAxJrQ+6Uo6+ZnNBv0/1KNiK03Bjf5/bokrkJbRKC0dsFdefcadCnQyNS/jkyxKzRo9zH8FGP3d2zSSDaehXbI4BlS4yhlwJ75Bz9AHLaElgCIoBtstsy8gJQr8IPA8D+m/f/fGTrIc4kcxfddDzKv31I0W7hEVOqB7ps6T3p6iww1XudYaki/LbGV+d3Bspe5r8RaCqz1iYFLuUCmEgqv+hAmcsd1mbtExfyR3T6QzwQYfzY/B+eMD3kfi/RfHYTxIWJril1a7AxwhJcHnnB2KYZxF5NIJRJTPIZ3vecmFjrOWdXPVtb29lpHICH2TWlKczfZQaTxNNmd6h6qYaq0QTAQhsSZWR8tJ7626bxM+N6MY59lDBU7g5K6AcGDddOWU5UB3TcPFLC9vFg+feY9jt6lIZCjzn6UiZ/y9OdKWu8j6+9PhphbEiE+IbZuUxqx1G2KRSJWahFn7F2nLlSSYexSIUX+CCum723msfwsN5MQbvfRnrlNz/6upbFyDaohk=
      skip_cleanup: true
      file_glob: true
      file: '*.vsix'
      on:
          repo: xsburg/vscode-javascript-booster
          tags: true
          condition: '$TRAVIS_OS_NAME = osx'
notifications:
    email:
        on_success: change
